apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2
  labels: 
   app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      version: v2.0.0 
  template:
    metadata:
      labels:
        app: my-app
        version: v2.0.0
    spec:
      containers:
      - name: my-app
        image: clumumba95/hello-world-py
        resources:
          limits:
           memory: "256Mi"
           cpu: "200m"
          requests:
           memory: "128Mi"
           cpu: "100m"