apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deploments", "service", "deamonsets", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  